### ISSUE TITLE
There is an error when opening the website

### ISSUE THREAD

**Issue by xzyl4303** [manga-download/haruneko#536]
[✖️](javascript:window.close();)
Failed to create an instance of type <T> for platform 'chromium'!
InternalError: Failed to create an instance of type <T> for platform 'chromium'!
    at PlatformInstanceActivator.Fail (http://localhost:3000/src/engine/platform/PlatformInstanceActivator.ts:18:11)
    at Object.chromium (http://localhost:3000/src/engine/platform/PlatformInstanceActivator.ts:7:36)
    at PlatformInstanceActivator.Create (http://localhost:3000/src/engine/platform/PlatformInstanceActivator.ts:25:36)
    at CreateAppWindow (http://localhost:3000/src/engine/platform/AppWindow.ts:5:142)
    at http://localhost:3000/src/index.ts:32:23
    at http://localhost:3000/src/index.ts:52:3

**Comment by Sheepux** [comment]
you don't run it with your browser, start the client (read the instructions)
