### ISSUE TITLE
Mixed content problem when downloading using binary release

### ISSUE THREAD

**Issue by wow2134** [manga-download/haruneko#754]
first of all thank you
since [you said using haruneko](https://github.com/manga-download/hakuneko/issues/7327#issuecomment-2283849157).
since there is this [issue](https://github.com/manga-download/hakuneko/issues/7062#issuecomment-2096975117). finally i can download from doujindesu using haruneko 😄 

now back to the problem..
when i try to download from [komiktap](https://komiktap.info/), there is only bin file in the folder. i thought this is only in 1 title, but it turns out all titles.

![ss1](https://github.com/user-attachments/assets/5898e3dc-3149-4926-903c-803923f884f9)

I think the image is corrupted from the website. But there is no problem on the website

![ss2](https://github.com/user-attachments/assets/4da00f07-c1ed-4c15-953e-71a81072ad4f)

because it didn't work to download on komiktap, I tried downloading on [komikindo.info](https://komikindo.info/) but the result was the same, while [doujinku.xyz](https://doujinku.xyz/) displays a "Failed to fetch" notification.
I've used hakuneko but the result is still only a bin file in the folder

**Comment by MikeZeDev** [comment]
First: ONE WEBSITE PER ISSUE PLEASE 🙏 

* Komiktap server its just that their server is returning crappy type, images are fine. See the "application/octet stream? "
it should have been image/something.. 

![image](https://github.com/user-attachments/assets/d4d2e3aa-ddd0-4388-834e-ad2e55af7aac)

You can rename your files if you want (replace the bin to jpeg or webp), they are fine

* Please name a problematic manga + chapter on [komikindo.info](https://komikindo.info/) that i can test

* Please name a problematic manga + chapter on doujinku that i can test. I cant reproduce the problem.

**Comment by wow2134** [comment]
> 
>     * Please name a problematic manga + chapter on doujinku that i can test. I cant reproduce the problem.

1. Name of connector : [doujinku.xyz](https://doujinku.xyz/)
2. Name of manga : https://doujinku.xyz/manga/milf-hunting-in-another-world/
3. Name of chapter : https://doujinku.xyz/milf-hunting-in-another-world-chapter-40/

![gambar](https://github.com/user-attachments/assets/1bbf4ede-b824-466a-80a2-7085bc31b4b3)

Failed to fetch
TypeError: Failed to fetch
    at ae.Fetch (https://haruneko.pages.dev/M03N76XJ/InteractiveFileContentProvider.js:2:2125)
    at async Ou.action (https://haruneko.pages.dev/M03N76XJ/HakuNeko.js:1:21558)
    at async Ou.Run (https://haruneko.pages.dev/M03N76XJ/index.js:2:29883)
    at async wc.Run (https://haruneko.pages.dev/M03N76XJ/index.js:2:31368)
Failed to fetch
TypeError: Failed to fetch
    at ae.Fetch (https://haruneko.pages.dev/M03N76XJ/InteractiveFileContentProvider.js:2:2125)
    at async Ou.action (https://haruneko.pages.dev/M03N76XJ/HakuNeko.js:1:21558)
    at async Ou.Run (https://haruneko.pages.dev/M03N76XJ/index.js:2:29883)
    at async wc.Run (https://haruneko.pages.dev/M03N76XJ/index.js:2:31368)
etc...

**Comment by wow2134** [comment]
> 
>     * Please name a problematic manga + chapter on [komikindo.info](https://komikindo.info/) that i can test

1. Name of connector : [komikindo.info](https://komikindo.info/)
2. Name of manga : https://komikindo.info/series/milf-hunting-in-another-world/
3. Name of chapter : https://komikindo.info/milf-hunting-in-another-world-chapter-40/

![gambar](https://github.com/user-attachments/assets/8a273b48-8895-4bb4-8778-cebcde5f95c0)

komikindo.info now has the same problem as [doujinku.xyz](https://doujinku.xyz/), but previously I could still download, even though there was only a bin file in the folder.

**Comment by MikeZeDev** [comment]
Ok the problem is clear. For both websites.

Its Mixed Content , same problem than here https://github.com/manga-download/haruneko/issues/713 (well there was a bug causing mixed content, here its the website fault)

Website is https, pictures links are http. Its damn 2024, why the hell their links are not updated to https.... :/
Stone age is over.

We have no immediate "clean" fix for that . You have 2 solutions : 

* use another website
* Run haruneko from source code by using instructions on the github page. That is way more complicated that just launching the exe. 🤷

**Comment by wow2134** [comment]
> Its Mixed Content , same problem than here #713 (well there was a bug causing mixed content, here its the website fault)
> 
> Website is https, pictures links are http. Its damn 2024, why the hell their links are not updated to https.... :/ Stone age is over.
> 

haha..
okay thanks for the explanation.

luckily we still have 2 mirror websites that are still working,
like manhwaland and kombatch..

next i will try this https://github.com/manga-download/haruneko/issues/713#issuecomment-2254609750

**Comment by ronny1982** [comment]
> Its damn 2024, why the hell their links are not updated to https.... :/ Stone age is over.

Because transferring these non-sensitive images via `HTTPS` makes no sense (`HTTP` is faster, does not require a certificate, ...)

**Comment by MikeZeDev** [comment]
Yeah but modern browsers may yell about mixed content/ refuse to load content.

**Comment by MikeZeDev** [comment]
Apparently, just adding 

```html
 <meta http-equiv="Content-Security-Policy" content="upgrade-insecure-requests">
```

to Haruneko main html page works. Not sure about security implications, and it may fail on some servers not supporting https but its already non working on such servers.

https://github.com/manga-download/haruneko/pull/1115 (Run from deployment url to test)

![Image](https://github.com/user-attachments/assets/3c5c9b6c-0574-42d0-8e16-2821564fb891)

**Comment by Sheepux** [comment]
This would apply to any url and not just images.

> Because transferring these non-sensitive images via HTTPS makes no sense (HTTP is faster, does not require a certificate, ...)

I do consider Image URL as a privacy concern because the "kind of content" you're reading/downloading is not something someone else should know (even more when we have hentai connectors).


Note: the URL
http://static.hq-now.com/hqs/hqs/uploads/picture/image/365154/100_copy.jpg
redirects itself to HTTPs
https://static.hq-now.com/hqs/hqs/uploads/picture/image/365154/100_copy.jpg

I propose the following:
- we only have https connectors (reject http websites)
- replace all http url to https on images we find when fetching chapters images

**Comment by MikeZeDev** [comment]
Like mentioned on the PR, we should perhaps consider upgrading http image requests using the appropriate header in GET request.
It would have way less impact that change that CSP for the whole app.

**Comment by ronny1982** [comment]
Addressed in https://github.com/manga-download/haruneko/commit/c6f69248f1d68304bc35c1c5c69fb2ee8a286cbb, please download and use the latest release

**Comment by MikeZeDev** [comment]
Hum. I didnt want to got that way (the command line) but if you are fine with it.

**Comment by ronny1982** [comment]
A command line switch would be required either way:
- Enable mixed-content: Add switch to `NW`
- Disable mixed-content: Add switch to `Electron`
