### ISSUE TITLE
Errors  with ScansMangas (ME)

### ISSUE THREAD

**Issue by didierGuieu** [manga-download/haruneko#757]
Hi
The following error is raised when I try to download somethong from ScansMangas (ME).

```
Cannot read properties of undefined (reading 'map')
TypeError: Cannot read properties of undefined (reading 'map')
    at Bp.it (https://haruneko.pages.dev/M07GMN0R/HakuNeko.js:1:21221)
    at async Ce.Update (https://haruneko.pages.dev/M07GMN0R/InteractiveFileContentProvider.js:2:9895)
    at async DownloadTask.Run (https://haruneko.pages.dev/M07GMN0R/DownloadTask.js:11:26520)
    at async Xwe.Process (https://haruneko.pages.dev/M07GMN0R/HakuNeko.js:1523:56800)
```

The same error occurs with HaruNeko

**Comment by MikeZeDev** [comment]
Manga? Chapter?

**Comment by didierGuieu** [comment]
Here is the requested informations
<img width="532" alt="image" src="https://github.com/user-attachments/assets/fdc18eee-d242-4bfd-af92-8a19ed561770">

**Comment by MikeZeDev** [comment]
A bit disturbing to see an Hakuneko screenshot in a Haruneko ticket but ok :D
