### ISSUE TITLE
[ReadComicOnlie.li] "Error: Unable to get pictures after more than 10 tries !"

### ISSUE THREAD

**Issue by Vandino86** [manga-download/haruneko#778]
I was trying to download a certain comic with from ReadComicOnline.li (NOT Read Comics Online.ru) using HaruNeko NW.js (canary • 2024-08-02) and it gave me the following error for each issue/chapter:

```
Error: Unable to get pictures after more than 10 tries !
 > Error: Error: Unable to get pictures after more than 10 tries !
    at DownloadTask.Run (https://haruneko.pages.dev/M1AO3F2X/DownloadTask.js:11:27044)
    at async wwe.Process (https://haruneko.pages.dev/M1AO3F2X/HakuNeko.js:1528:56339)
```

I tried downloading a few other comics. Some had the same issue while others downloaded just fine.

**Comment by ronny1982** [comment]
[Fixed](https://github.com/manga-download/haruneko/commit/2845228fb65e738183d078901d9de00ab8ae7cb1) for now, but they will probably adapt very soon to block HaruNeko again...

**Comment by Vandino86** [comment]
> [Fixed](https://github.com/manga-download/haruneko/commit/2845228fb65e738183d078901d9de00ab8ae7cb1) for now, but they will probably adapt very soon to block HaruNeko again...

Thank you so much! I just tested this on 3 different comics and it mostly works except there was a single page that was not downloaded as a ~400 KB - ~2 MB JPEG as expected; it was instead a 1.68 KB .bin. Opening this file in a text editor revealed the following contents:

```HTML
<!DOCTYPE html>
<html lang=en>
  <meta charset=utf-8>
  <meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">
  <title>Error 500 (Server Error)!!1</title>
  <style>
    *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}
  </style>
  <a href=//www.google.com/><span id=logo aria-label=Google></span></a>
  <p><b>500.</b> <ins>That’s an error.</ins>
  <p>The server encountered an error and could not complete your request.<p>If the problem persists, please <A HREF="http://www.google.com/support/">report</A> your problem and mention this error message and the query that caused it.  <ins>That’s all we know.</ins>
```

I tried re-downloading the chapter/issue and it downloaded the page as a JPEG that time, thankfully. I think this should be fixed so that each page should be checked to see if it actually got properly downloaded (and if not, then try to re-download the page).
