### ISSUE TITLE
[Kakaopage] chapter list does not appear

### ISSUE THREAD

**Issue by NinjaScoutZ** [manga-download/haruneko#951]
![image](https://github.com/user-attachments/assets/ac99ac03-c630-4a8d-a43a-54ac467b9a5b)

**Comment by NinjaScoutZ** [comment]
21화
The request failed due to the following GraphQL error(s):
구매하지 않은 상품입니다.
 > Ju<FetchProvider_FetchGraphQL_AggregateError>
    at NodeWebkitFetchProvider.FetchGraphQL (https://haruneko.pages.dev/M5IWJZ51/DownloadTask.js:11:34104)
    at async Xo.FetchPages (https://haruneko.pages.dev/M5IWJZ51/HakuNeko.js:798:1079)
    at async b.Update (https://haruneko.pages.dev/M5IWJZ51/DownloadTask.js:12:6430)
    at async DownloadTask.Run (https://haruneko.pages.dev/M5IWJZ51/DownloadTask.js:12:7734)
    at async Qfe.Process (https://haruneko.pages.dev/M5IWJZ51/HakuNeko.js:1709:57526)
![image](https://github.com/user-attachments/assets/97fe89c5-511f-4012-a034-466f3c1a22db)
